SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
SCALE = 40
NUM_BLOCKS_WIDTH = SCREEN_WIDTH // SCALE
NUM_BLOCKS_HEIGT = SCREEN_HEIGHT // SCALE

BOMB_RADIUS = 2
EXPLODE_TIME = 300
BOMB_DELAY = 2000

MAX_BOXES = 100

QUIT_KEY = 27  # Escape
